SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `ANS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Time` text NOT NULL,
  `TransactionID` bigint(20) NOT NULL,
  `ItemID` int(10) NOT NULL,
  `ItemName` varchar(100) NOT NULL,
  `MerchantName` varchar(100) NOT NULL,
  `PayerName` varchar(100) NOT NULL,
  `PayerKey` varchar(36) NOT NULL,
  `ReceiverName` varchar(100) NOT NULL,
  `ReceiverKey` varchar(36) NOT NULL,
  `PaymentGross` varchar(12) NOT NULL,
  `Location` varchar(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=14 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
